[context.production.environment]
  HUGO_VERSION = "0.99.1"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.99.1"
[build]
  publish = "public"
  command = "hugo --gc && node _tools/newpostcheck.js"
